rewrite fix

diff --git a/tennessee/cloud/build b/tennessee/cloud/build
--- a/tennessee/cloud/build
+++ b/tennessee/cloud/build
@@ -1,38 +1,61 @@
 #!/bin/bash -e
 
 function main() {
+  
   cd "$(dirname "$0")" || { err "unable to change directory"; return 2; }
+  err "building $(basename "$PWD")"
+
+  [ -f settings ] && { source settings; }
+  [ -f ../settings ] && { source ../settings; }
 
   local missingSetting
   missingSetting=false
   [[ "$TENANT" ]] || { err "Missing TENANT"; missingSetting=true; }
   [[ "$CLOUD" ]] || { err "Missing CLOUD"; missingSetting=true; }
   [[ "$GROUP" ]] || { err "Missing GROUP"; missingSetting=true; }
-  "$missingSetting" && { err "Did you update and source settings?"; return 3; }
+  "$missingSetting" && { err "Failure building $(basename "$PWD"); see above"; return $?; }
+
+  _setup || { err "Failure building $(basename "$PWD"); see above"; return $?; }
+  _main || { err "Failure building $(basename "$PWD"); see above"; return $?; }
+  return 0
+}
+
+function _main() {
 
   echo "#!/bin/bash -e" > create
-  echo "xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/secops.yaml" >> create
+  echo "$xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/secops.yaml" >> create
   chmod +x create
 
   [[ "$CLOUD_NTP" ]] && {
     # shellcheck disable=SC2086
     update prisma/ntp.yaml $CLOUD_NTP
-    echo "xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/ntp.yaml" >> create
+    echo "$xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/ntp.yaml" >> create
   }
 
   [[ "$CLOUD_DNS" ]] && {
     # shellcheck disable=SC2086
     update prisma/dns.yaml $CLOUD_DNS
-    echo "xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/dns.yaml" >> create
+    echo "$xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/dns.yaml" >> create
   }
 
   [[ "$META_DATA_API" ]] && {
     # shellcheck disable=SC2086
     update prisma/metadataapi.yaml $META_DATA_API
-    echo "xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/metadataapi.yaml" >> create
+    echo "$xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/metadataapi.yaml" >> create
   }
 
   return 0
+}
+
+function _setup() {
+  thisDir="$PWD"
+  cd ../bin/$(uname | tr '[:upper:]' '[:lower:]')/$(uname -m)
+  jq="$PWD/jq"
+  yq="$PWD/yq"
+  cd "$thisDir"
+  cd ../bin/scripts
+  xapoctl="$PWD/xapoctl"
+  cd "$thisDir"
 }
 
 function update() {
diff --git a/tennessee/group/build b/tennessee/group/build
--- a/tennessee/group/build
+++ b/tennessee/group/build
@@ -1,14 +1,26 @@
 #!/bin/bash -e
 
 function main() {
+ 
   cd "$(dirname "$0")" || { err "unable to change directory"; return 2; }
+  err "building $(basename "$PWD")"
+
+  [ -f settings ] && { source settings; }
+  [ -f ../settings ] && { source ../settings; }
 
   local missingSetting
   missingSetting=false
   [[ "$TENANT" ]] || { err "Missing TENANT"; missingSetting=true; }
   [[ "$CLOUD" ]] || { err "Missing CLOUD"; missingSetting=true; }
   [[ "$GROUP" ]] || { err "Missing GROUP"; missingSetting=true; }
-  "$missingSetting" && { err "Did you update and source settings?"; return 3; }
+  "$missingSetting" && { err "Failure building $(basename "$PWD"); see above"; return $?; }
+
+  _setup || { err "Failure building $(basename "$PWD"); see above"; return $?; }
+  _main || { err "Failure building $(basename "$PWD"); see above"; return $?; }
+  return 0
+}
+
+function _main() {
 
   echo "#!/bin/bash -e" > create
   chmod +x create
@@ -20,7 +32,7 @@ function main() {
     }
     # shellcheck disable=SC2086
     update prisma/dns.yaml $KUBE_DNS
-    echo "xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/dns.yaml" >> create
+    echo "$xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/dns.yaml" >> create
   }
 
   [[ "$KUBE_NODES" ]] && {
@@ -30,10 +42,31 @@ function main() {
     }
     # shellcheck disable=SC2086
     update prisma/nodes.yaml $KUBE_NODES
-    echo "xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/nodes.yaml" >> create
+    echo "$xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/nodes.yaml" >> create
+  }
+
+  [[ "$KUBE_API" ]] && {
+    [ "$KUBE_API" == "auto" ] && {
+      KUBE_API=$(kubectl get svc -n default -o=jsonpath="{.items[*].spec.clusterIP}")
+      [[ "$KUBE_API" ]] || { err "Unable to resolve kube api; please set KUBE_API in settings"; return 3; }
+    }
+    # shellcheck disable=SC2086
+    update prisma/kubeapi.yaml $KUBE_API
+    echo "$xapoctl api import -n /$TENANT/$CLOUD/$GROUP --file $PWD/prisma/kubeapi.yaml" >> create
   }
 
   return 0
+}
+
+function _setup() {
+  thisDir="$PWD"
+  cd ../bin/$(uname | tr '[:upper:]' '[:lower:]')/$(uname -m)
+  jq="$PWD/jq"
+  yq="$PWD/yq"
+  cd "$thisDir"
+  cd ../bin/scripts
+  xapoctl="$PWD/xapoctl"
+  cd "$thisDir"
 }
 
 function update() {
@@ -43,14 +76,14 @@ function update() {
   shift
   # shellcheck disable=SC2068
   for node in $@; do
-    yq -i e ".data.externalnetworks[0].entries += [\"$node\"]" "$file"
+    $yq -i e ".data.externalnetworks[0].entries += [\"$node\"]" "$file"
   done
 }
 
 function clean() {
   local file
   file=$1
-  yq -i e "del(.data.externalnetworks[0].entries)" "$file"
+  $yq -i e "del(.data.externalnetworks[0].entries)" "$file"
 }
 
 function err() { echo "$@" 1>&2; }
diff --git a/tennessee/nashville/build b/tennessee/nashville/build
--- a/tennessee/nashville/build
+++ b/tennessee/nashville/build
@@ -1,30 +1,62 @@
 #!/bin/bash -e
 
 function main() {
+
   cd "$(dirname "$0")" || { err "unable to change directory"; return 2; }
+  err "building $(basename "$PWD")"
+
+  [ -f settings ] && { source settings; }
+  [ -f ../settings ] && { source ../settings; }
 
   local missingSetting
   missingSetting=false
   [[ "$TENANT" ]] || { err "Missing TENANT"; missingSetting=true; }
   [[ "$CLOUD" ]] || { err "Missing CLOUD"; missingSetting=true; }
   [[ "$GROUP" ]] || { err "Missing GROUP"; missingSetting=true; }
-  "$missingSetting" && { err "Did you update and source settings?"; return 3; }
+  "$missingSetting" && { err "Failure building $(basename "$PWD"); see above"; return $?; }
+
+  _setup || { err "Failure building $(basename "$PWD"); see above"; return $?; }
+  _main || { err "Failure building $(basename "$PWD"); see above"; return $?; }
+  return 0
+}
+
+function _main() {
   echo_create > create
   echo_delete > delete
   echo_restart > restart
+
+  rm -rf k8s
+  cp -r _k8s k8s
+  [[ "$ISTIO_ENABLED" ]] && { 
+    err "Istio is enabled"
+    cp istio/* k8s;
+  } || {
+    err "Istio is not enabled"
+  }
+
   chmod +x create delete restart
   return 0
+}
+
+function _setup() {
+  thisDir="$PWD"
+  cd ../bin/$(uname | tr '[:upper:]' '[:lower:]')/$(uname -m)
+  jq="$PWD/jq"
+  yq="$PWD/yq"
+  cd "$thisDir"
+  cd ../bin/scripts
+  xapoctl="$PWD/xapoctl"
+  cd "$thisDir"
 }
 
 function echo_create()
 {
 cat <<EOF
 #!/bin/bash -e
-cd "\$(dirname "\$0")"
 kubectl apply -f $PWD/k8s/ns.yaml
 sleep 2
 kubectl apply -f $PWD/k8s
-xapoctl api import -n "/$TENANT/$CLOUD/$GROUP/$(basename "$PWD")" --file "$PWD"/prisma/config.yaml
+$xapoctl api import -n "/$TENANT/$CLOUD/$GROUP/$(basename "$PWD")" --file "$PWD"/prisma/config.yaml
 EOF
 }
 
@@ -44,7 +76,7 @@ function main() {
     err "Kubernetes Namespace \$ns does not exist"
   }
 
-  id=\$(apoctl api list namespaces -n "/$TENANT/$CLOUD/$GROUP" -f "name==/$TENANT/$CLOUD/$GROUP/$(basename "$PWD")" | jq -r '.[].ID')
+  id=\$($xapoctl api list namespaces -n "/$TENANT/$CLOUD/$GROUP" -f "name==/$TENANT/$CLOUD/$GROUP/$(basename "$PWD")" | $jq -r '.[].ID')
   [[ "\$id" ]] && {
     err "Deleting Prisma Namespace \$ns with id \$id"
     apoctl api delete namespace "/$TENANT/$CLOUD/$GROUP/$(basename "$PWD")" || rc=3
